spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/calvin
    username: root
    password: calvin
  jpa:
    open-in-view: false
    show-sql: true

logging:
  level:
    root: debug
