spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/calvin
    username: root
    password: calvin
    data: data.sql
    schema: schema.sql
  jpa:
    open-in-view: false
    show-sql: true

logging:
  level:
    root: debug

server:
  port: 8443
  ssl:
    key-store: mykes.jks
    key-store-password: letmein
    key-password: letmein

taco:
  orders:
    pageSize: 10